#!/usr/bin/env python3
"""Verify MANIFEST.sha256.json against disk content.

Used by the manifest-verify GitHub Actions workflow but designed to be
runnable locally by anyone (`python scripts/ci/verify_manifest.py`).

Behavior:
  - Real files on disk:   recompute SHA256 + byte count, compare to manifest
  - Git LFS pointer stubs: skip (manifest preserves real-content hash)
  - Build artifacts:       skip (gitignored, regenerated by pdflatex)
  - Missing real files:    FAIL with a list of paths

Exit code:
  0  if all real files match the manifest
  1  if any real file is missing or its hash does not match

Designed to run on a fresh clone WITHOUT `git lfs pull`. LFS-tracked
files appear as 130-byte pointer stubs and are skipped cleanly.
"""
from __future__ import annotations

import hashlib
import json
import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
MANIFEST_PATH = REPO_ROOT / "MANIFEST.sha256.json"

LFS_PREFIX = b"version https://git-lfs.github.com/spec/v1"

GITIGNORED_SUFFIXES = (".aux", ".bbl", ".blg", ".log", ".out", ".toc")


def is_lfs_stub(path: Path) -> bool:
    try:
        with open(path, "rb") as fh:
            return fh.read(64).startswith(LFS_PREFIX)
    except OSError:
        return False


def main() -> int:
    with open(MANIFEST_PATH) as fh:
        manifest = json.load(fh)

    ok = 0
    lfs_stubs = 0
    gitignored = 0
    missing: list[str] = []
    mismatches: list[tuple[str, str, str]] = []

    for rel_path, expected in manifest.items():
        if not isinstance(expected, dict):
            mismatches.append((rel_path, "BAD_FORMAT", repr(expected)))
            continue

        path = REPO_ROOT / rel_path
        if not path.is_file():
            if rel_path.endswith(GITIGNORED_SUFFIXES):
                gitignored += 1
            else:
                missing.append(rel_path)
            continue

        if is_lfs_stub(path):
            # Manifest preserves the real-content hash; we cannot verify
            # against a 130-byte pointer stub. Workstation LFS pull will.
            lfs_stubs += 1
            continue

        with open(path, "rb") as fh:
            content = fh.read()
        actual_sha = hashlib.sha256(content).hexdigest()
        actual_bytes = len(content)
        if (expected.get("sha256") == actual_sha
                and expected.get("bytes") == actual_bytes):
            ok += 1
        else:
            mismatches.append((
                rel_path,
                f"manifest:{expected.get('sha256','?')[:16]}({expected.get('bytes')}b)",
                f"disk:{actual_sha[:16]}({actual_bytes}b)",
            ))

    print("Manifest verification")
    print("=====================")
    print(f"  OK (real-file hashes match):              {ok}")
    print(f"  LFS pointer stubs (skipped):              {lfs_stubs}")
    print(f"  Gitignored build artifacts (skipped):     {gitignored}")
    print(f"  Missing real files (failure if non-zero): {len(missing)}")
    print(f"  Hash mismatches (failure if non-zero):    {len(mismatches)}")

    if missing:
        print("\nMISSING:")
        for p in missing[:25]:
            print(f"  - {p}")
        if len(missing) > 25:
            print(f"  ... and {len(missing) - 25} more")
    if mismatches:
        print("\nMISMATCHES:")
        for tup in mismatches[:25]:
            print(f"  - {tup}")
        if len(mismatches) > 25:
            print(f"  ... and {len(mismatches) - 25} more")

    fail = bool(missing or mismatches)
    return 1 if fail else 0


if __name__ == "__main__":
    sys.exit(main())
