#!/usr/bin/env python3
"""Verify MANIFEST.sha256.json against disk content.

Used by the manifest-verify GitHub Actions workflow but designed to be
runnable locally by anyone (`python scripts/ci/verify_manifest.py`).

Behavior:
  - Real files on disk:   recompute SHA256 + byte count, compare to manifest
  - Git LFS pointers: verify declared real-content SHA-256 and byte size
    against the manifest (the actual LFS payload is NOT downloaded)
  - Build artifacts:       skip (gitignored, regenerated by pdflatex)
  - Missing real files:    FAIL with a list of paths

Exit code:
  0  if all real files match the manifest
  1  if any real file is missing or its hash does not match

Designed to run on a fresh clone WITHOUT `git lfs pull`. LFS pointers
are verified against the manifest; this does not attest to the existence
or integrity of remotely stored LFS payloads.
"""
from __future__ import annotations

import hashlib
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
MANIFEST_PATH = REPO_ROOT / "MANIFEST.sha256.json"

LFS_PREFIX = b"version https://git-lfs.github.com/spec/v1"

GITIGNORED_SUFFIXES = (".aux", ".bbl", ".blg", ".log", ".out", ".toc")

# Binary suffixes whose bytes must match exactly; never LF-normalize these.
# Stored lowercase; the suffix check lowercases the path so matching is
# case-insensitive regardless of how a future entry is cased.
BINARY_SUFFIXES = (".npz", ".npy", ".png", ".pdf", ".jpg", ".jpeg", ".gif",
                   ".ico", ".whl")


def is_lfs_stub(path: Path) -> bool:
    try:
        with open(path, "rb") as fh:
            return fh.read(64).startswith(LFS_PREFIX)
    except OSError:
        return False


def lfs_pointer_metadata(path: Path) -> tuple[str, int] | None:
    """Extract LFS object ID and size from a strictly formed Git pointer.

    A pointer's OID is the SHA-256 of the *real* file, but verifying the
    pointer does not verify remote object availability or download its bytes.
    Reject malformed or extended stubs instead of silently trusting them.
    """
    try:
        content = path.read_bytes()
    except OSError:
        return None
    if len(content) > 1024:
        return None
    lines = content.splitlines()
    if len(lines) != 3 or lines[0] != LFS_PREFIX:
        return None
    oid = re.fullmatch(rb"oid sha256:([0-9a-f]{64})", lines[1])
    size = re.fullmatch(rb"size (0|[1-9][0-9]*)", lines[2])
    if oid is None or size is None:
        return None
    return oid.group(1).decode("ascii"), int(size.group(1))


def main() -> int:
    with open(MANIFEST_PATH) as fh:
        manifest = json.load(fh)

    ok = 0
    lfs_pointers_verified = 0
    gitignored = 0
    missing: list[str] = []
    mismatches: list[tuple[str, str, str]] = []

    for rel_path, expected in manifest.items():
        if not isinstance(expected, dict):
            mismatches.append((rel_path, "BAD_FORMAT", repr(expected)))
            continue

        path = REPO_ROOT / rel_path
        if not path.is_file():
            if rel_path.endswith(GITIGNORED_SUFFIXES):
                gitignored += 1
            else:
                missing.append(rel_path)
            continue

        if is_lfs_stub(path):
            metadata = lfs_pointer_metadata(path)
            if metadata is None:
                mismatches.append((rel_path, "valid LFS pointer", "malformed LFS pointer"))
            else:
                oid, size = metadata
                if expected.get("sha256") == oid and expected.get("bytes") == size:
                    lfs_pointers_verified += 1
                else:
                    mismatches.append((
                        rel_path,
                        f"manifest:{str(expected.get('sha256', '?'))[:16]}({expected.get('bytes')}b)",
                        f"LFS pointer:{oid[:16]}({size}b)",
                    ))
            continue

        with open(path, "rb") as fh:
            content = fh.read()
        actual_sha = hashlib.sha256(content).hexdigest()
        actual_bytes = len(content)
        if (expected.get("sha256") == actual_sha
                and expected.get("bytes") == actual_bytes):
            ok += 1
            continue

        # Raw bytes did not match. The manifest stores the LF-committed form
        # of text files (what git tracks). On a Windows checkout with
        # core.autocrlf=true the working tree carries CRLF line endings, which
        # inflates byte count and changes the hash even though no content was
        # edited. For non-binary files, retry against the LF-normalized form so
        # an intact file does not register a spurious mismatch. This mirrors
        # verify_prereg_locks.py. Binary files are never normalized.
        if not rel_path.lower().endswith(tuple(s.lower() for s in BINARY_SUFFIXES)):
            lf = content.replace(b"\r\n", b"\n")
            lf_sha = hashlib.sha256(lf).hexdigest()
            if (expected.get("sha256") == lf_sha
                    and expected.get("bytes") == len(lf)):
                ok += 1
                continue

        mismatches.append((
            rel_path,
            f"manifest:{expected.get('sha256','?')[:16]}({expected.get('bytes')}b)",
            f"disk:{actual_sha[:16]}({actual_bytes}b)",
        ))

    print("Manifest verification")
    print("=====================")
    print(f"  OK (real-file hashes match):              {ok}")
    print(f"  LFS OIDs/sizes match (payloads not read):  {lfs_pointers_verified}")
    print(f"  Gitignored build artifacts (skipped):     {gitignored}")
    print(f"  Missing real files (failure if non-zero): {len(missing)}")
    print(f"  Hash mismatches (failure if non-zero):    {len(mismatches)}")

    if missing:
        print("\nMISSING:")
        for p in missing[:25]:
            print(f"  - {p}")
        if len(missing) > 25:
            print(f"  ... and {len(missing) - 25} more")
    if mismatches:
        print("\nMISMATCHES:")
        for tup in mismatches[:25]:
            print(f"  - {tup}")
        if len(mismatches) > 25:
            print(f"  ... and {len(mismatches) - 25} more")

    fail = bool(missing or mismatches)
    return 1 if fail else 0


if __name__ == "__main__":
    sys.exit(main())
